version: '3'
services:
  web:
    container_name: examplebackend
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
      - elasticsearch
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9200
      - 9200:9200
volumes:
  esdata:
